add: hw 2
Armazok/react-20240513 pull request #2
Opened 2024-05-21 20:03 UTC by Armazok

2024-05-22 06:51 UTC, Armazok commented
Приветствую Артём

У вас есть возможность оценивать мои коммиты по всей строгости?

2024-05-23 16:33 UTC, SArchieEdu requested changes

2024-05-23 16:33 UTC, SArchieEdu commented on src/App.jsx
>  function App() {
компонент сильно перегружен. Необходимо разделить его на части, даже если вы вынесли логику отрисовки списков и подобное. Сейчас у вас добавилась еще и логика хуков. Разделите как мы делали на лекции, сильно проще станет

2024-05-23 16:33 UTC, SArchieEdu commented on src/App.jsx
> +    const hiddenRestaurant = (id) => {
скорее selectTab

2024-05-24 08:13 UTC, merged